exclude: ^(docs)$
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
        args: [ -m ]
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
    -   id: reorder-python-imports
        args: [--application-directories, '.:src', --py38-plus]
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: 'v1.9.0'
#     hooks:
#     -   id: mypy
-   repo: https://github.com/PyCQA/flake8
    rev: '7.0.0'
    hooks:
    -   id: flake8
